# Generated by Django 4.2.20 on 2025-04-24 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('funeral', 'Похороны'), ('other', 'Другое')], max_length=50, verbose_name='Повод для сбора')),
                ('description', models.TextField(verbose_name='Описание')),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Целевая сумма')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Собранная сумма')),
                ('contributors_count', models.PositiveIntegerField(default=0, verbose_name='Количество донатеров')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collect_covers/', verbose_name='Обложка сбора')),
                ('deadline', models.DateTimeField(verbose_name='Дата и время окончания сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя и фамилия пользователя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания платежа')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.collect', verbose_name='Сбор')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
